### PR TITLE
http2-client: implement some 'no HTTP/2' heuristics

### LINKED ISSUE #13: http2-client should suppress uncleanShutdown errors
### Expected behavior

Unclean TLS shutdown should be ignored when the request has been fully delivered.

### Actual behavior

Unclean TLS shutdown is reported in the terminal.

### Steps to reproduce

1. Attempt to contact `https://microsoft.com`

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

Sometimes, servers don't speak HTTP/2 and we didn't properly detect
that. There's no great way to detecting that but no we support the three
most common ones:

1. uncleanShutdown before the first byte was sent
2. server just sends a 'HTTP/1.x 400 Bad Request'
3. server immediately initiates (a clean) TLS shutdown

Modification:

- Heuristics for the two failures above
- Added a check script for the top sites, output similar to this:

```
testing      https://www.facebook.com/: curl HTTP/2 ok    ; NIO ok
testing       https://www.twitter.com/: curl HTTP/2 ok    ; NIO ok
testing        https://www.google.com/: curl HTTP/2 ok    ; NIO ok
testing       https://www.youtube.com/: curl HTTP/2 ok    ; NIO ok
testing     https://www.instagram.com/: curl HTTP/2 ok    ; NIO ok
testing      https://www.linkedin.com/: curl HTTP/2 ok    ; NIO ok
testing     https://www.wordpress.org/: curl HTTP/2 ok    ; NIO ok
testing     https://www.pinterest.com/: curl HTTP/2 ok    ; NIO ok
testing     https://www.wikipedia.org/: curl HTTP/2 ok    ; NIO ok
testing     https://www.wordpress.com/: curl HTTP/2 ok    ; NIO ok
testing      https://www.blogspot.com/: curl HTTP/2 ok    ; NIO ok
testing         https://www.apple.com/: curl HTTP/2 ok    ; NIO ok
testing         https://www.adobe.com/: curl HTTP/2 ok    ; NIO ok
testing        https://www.tumblr.com/: curl HTTP/2 ok    ; NIO ok
testing          https://www.youtu.be/: curl failed       ; NIO ok
testing        https://www.amazon.com/: curl HTTP/2 ok    ; NIO ok
testing            https://www.goo.gl/: curl HTTP/2 ok    ; NIO ok
testing         https://www.vimeo.com/: curl HTTP/1.x only; NIO correctly detected no HTTP/2
testing        https://www.flickr.com/: curl HTTP/2 ok    ; NIO ok
testing     https://www.microsoft.com/: curl HTTP/2 ok    ; NIO ok
testing         https://www.yahoo.com/: curl HTTP/2 ok    ; NIO ok
testing       https://www.godaddy.com/: curl HTTP/2 ok    ; NIO ok
testing            https://www.bit.ly/: curl HTTP/1.x only; NIO correctly detected no HTTP/2
testing            https://www.vk.com/: curl HTTP/2 ok    ; NIO ok
testing        https://www.reddit.com/: curl HTTP/2 ok    ; NIO ok
testing            https://www.w3.org/: curl HTTP/2 ok    ; NIO ok
testing         https://www.baidu.com/: curl HTTP/1.x only; NIO correctly detected no HTTP/2
testing       https://www.nytimes.com/: curl HTTP/2 ok    ; NIO ok
testing              https://www.t.co/: curl HTTP/2 ok    ; NIO ok
```

Result:

- Better UX for http2-client
- fixes #13

### CODE REVIEW

File: http2-client/Sources/http2-client/main.swift [hunk 1]
```diff
@@ -62,6 +64,54 @@ final class SendRequestHandler: ChannelInboundHandler {
...
+    enum Error: Swift.Error {
+        case serverDoesNotSpeakHTTP2
+    }
+
+    var bytesSeen = 0
+
+    func channelRead(context: ChannelHandlerContext, data: NIOAny) {
+        let buffer = self.unwrapInboundIn(data)
+        // this is a pretty terrible thing but some servers literally accept the "h2" ALPN and reply with a
+        // 'HTTP/1.x 400 Bad Request' response :(.
```
Comment (Lukasa) [inline http2-client/Sources/http2-client/main.swift]: I don't think this actually happens: I just think http2-client doesn't pay attention to the result of the ALPN negotiation. There's a user event fired that contains the result, and in all of these cases I think the result will be `nil`, which means "no protocol negotiated". You don't really need this hack.

Comment (weissi) [reply http2-client/Sources/http2-client/main.swift]: @Lukasa so I don't see a user event:

```
Channel registered in handler4
Channel became active in handler4
Channel user inbound event handshakeCompleted(negotiatedProtocol: nil) triggered in handler4
Channel read NIOAny { ByteBuffer { readerIndex: 0, writerIndex: 313, readableBytes: 313, capacity: 16384, slice: _ByteBufferSlice { 0..<16384 }, storage: 0x00007fd4c900b200 (16384 bytes) } } in handler4
buffer: HTTP/1.1 400 Bad Request
Server: Server
Date: Wed, 17 Apr 2019 10:18:42 GMT
Content-Type: text/html
Content-Length: 167
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>Server</center>
</body>
</html>

ERROR: serverDoesNotSpeakHTTP2
```

these debug handlers sit right after SSL

Comment (Lukasa) [reply http2-client/Sources/http2-client/main.swift]: This looks a lot like a user event to me:

```
Channel user inbound event handshakeCompleted(negotiatedProtocol: nil) triggered in handler4
```

Comment (weissi) [reply http2-client/Sources/http2-client/main.swift]: @Lukasa aaah, sorry! got it

Comment (weissi) [reply http2-client/Sources/http2-client/main.swift]: dfone
